Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import plotly.figure_factory as ff

# Add histogram data
x1 = np.random.randn(200) - 2
x2 = np.random.randn(200)
x3 = np.random.randn(200) + 2
x4 = np.random.randn(200) + 4

# Group data together
hist_data = [x1, x2, x3, x4]

group_labels = ['Group 1', 'Group 2', 'Group 3', 'Group 4']

# Create distplot with custom bin_size
fig = ff.create_distplot(hist_data, group_labels, bin_size=.2)
fig.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[4], line 15[0m
[1;32m     12[0m group_labels [38;5;241m=[39m [[38;5;124m'[39m[38;5;124mGroup 1[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mGroup 2[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mGroup 3[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mGroup 4[39m[38;5;124m'[39m]
[1;32m     14[0m [38;5;66;03m# Create distplot with custom bin_size[39;00m
[0;32m---> 15[0m fig [38;5;241m=[39m [43mff[49m[38;5;241;43m.[39;49m[43mcreate_distplot[49m[43m([49m[43mhist_data[49m[43m,[49m[43m [49m[43mgroup_labels[49m[43m,[49m[43m [49m[43mbin_size[49m[38;5;241;43m=[39;49m[38;5;241;43m.2[39;49m[43m)[49m
[1;32m     16[0m fig[38;5;241m.[39mshow()

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/plotly/figure_factory/_distplot.py:178[0m, in [0;36mcreate_distplot[0;34m(hist_data, group_labels, bin_size, curve_type, colors, rug_text, histnorm, show_hist, show_curve, show_rug)[0m
[1;32m    175[0m [38;5;28;01mif[39;00m rug_text [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    176[0m     rug_text [38;5;241m=[39m []
[0;32m--> 178[0m [43mvalidate_distplot[49m[43m([49m[43mhist_data[49m[43m,[49m[43m [49m[43mcurve_type[49m[43m)[49m
[1;32m    179[0m utils[38;5;241m.[39mvalidate_equal_length(hist_data, group_labels)
[1;32m    181[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(bin_size, ([38;5;28mfloat[39m, [38;5;28mint[39m)):

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/plotly/figure_factory/_distplot.py:47[0m, in [0;36mvalidate_distplot[0;34m(hist_data, curve_type)[0m
[1;32m     42[0m     [38;5;28;01mraise[39;00m exceptions[38;5;241m.[39mPlotlyError(
[1;32m     43[0m         [38;5;124m"[39m[38;5;124mcurve_type must be defined as [39m[38;5;124m"[39m [38;5;124m"[39m[38;5;124m'[39m[38;5;124mkde[39m[38;5;124m'[39m[38;5;124m or [39m[38;5;124m'[39m[38;5;124mnormal[39m[38;5;124m'[39m[38;5;124m"[39m
[1;32m     44[0m     )
[1;32m     46[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m scipy:
[0;32m---> 47[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m([38;5;124m"[39m[38;5;124mFigureFactory.create_distplot requires scipy[39m[38;5;124m"[39m)

[0;31mImportError[0m: FigureFactory.create_distplot requires scipy

